server:
  port: 8081
  servlet:
    session:
      timeout: 600s

host: 'localhost'

# This is keycloak from docker-compose.yml
keycloak:
  uri: 'http://${host}:8080'
  realm: "alfa-skillbox-keycloak"
spring:
  security:
    oauth2:
      client:
        # кладем spring.security.oauth2.client в OAuth2ClientProperties.class -> автоконфигурится ClientRegistration.class
        provider:
          keycloak:
            issuer-uri: '${keycloak.uri}/auth/realms/${keycloak.realm}'
            # 1. после вызова http://адрес_клиента/oauth2/authorization/{registrationId} инициализируется процесс OAuth2.0
            # клиент формирует uri_auth = ${authorization-uri}?response_type=code&client_id=${client-id}&scope=${scope}&state=redirect_uri=${redirect-uri}
            # и отправляет 302 ответ с Location=uri_auth, чтобы кейкллок начал процесс авторизации пользователя, и вернул
            # через редирект 302 ответ с Location=redirect_uri?code=&state= на клиента
            authorization-uri: '${keycloak.uri}/auth/realms/${keycloak.realm}/protocol/openid-connect/auth'
            # 2. Клиент, получая code и state, подставляет их в POST запрос на ${token-uri} и в ответ получает access_token, refresh_token, id_token
            token-uri: '${keycloak.uri}/auth/realms/${keycloak.realm}/protocol/openid-connect/token'
            # 3. После получения токенов клиент уже авторизованно обращается на ${userinfoUri} для получения информации о пользователе
            userinfoUri: "${keycloak.uri}/auth/realms/${keycloak.realm}/protocol/openid-connect/userinfo"
            # 4. Используется при запросе /userinfo
            user-name-attribute: 'preferred_username'
            end_session_endpoint: '${ukeycloak.uri}/auth/realms/${keycloak.realm}/protocol/openid-connect/logout'
            logout-url: '${keycloak.uri}/auth/realms/${keycloak.realm}/protocol/openid-connect/logout'
            logout-redirect-url: 'http://${host}:${server.port}/login'
        registration:
          ac-client:
            registrationId: 'ac-client'
            provider: 'keycloak'
            client-id: 'authorization-code-client'
            client-secret: 'auth-code-secret'
            authorization-grant-type: 'authorization_code'
            # важно указать openid в scope, если необходимо в Spring запустить процесс по протоколу openid-connect
            # а именно установить nonce в ссылке при формировании ${authorization-uri} в DefaultOAuth2AuthorizationRequestResolver
            # и из OAuth2LoginAuthenticationProvider: Section 3.1.2.1 Authentication Request - https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest scope
            # REQUIRED. OpenID Connect requests MUST contain the "openid" scope value
            scope: 'openid'
            redirect-uri: 'http://${host}:${server.port}/login/oauth2/code/keycloak'

rest:
  clients:
    ac-client:
      uri: "http://localhost:8083/resource-server/client-token"


logging:
  level:
    org.springframework: debug

management:
  endpoints:
    loggers:
      enabled: true
    web:
      exposure:
        include: loggers, health