host: 'localhost'
server:
  port: 8083
# This is keycloak from docker-compose.yml
keycloak:
  uri: 'http://${host}:8080'
  realm: "alfa-skillbox-keycloak"
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: '${keycloak.uri}/auth/realms/${keycloak.realm}/protocol/openid-connect/certs'

clients:
  permit:
    authorities:
      ac-client: "ROLE_resource-server"
      cc-client: "SCOPE_resource-server-scope"

logging:
  level:
    org.springframework: debug

management:
  endpoints:
    loggers:
      enabled: true
    web:
      exposure:
        include: loggers, health