version: '3.7'
services:
  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak-local
    networks:
      - keycloak-ldap
    environment:
      # через эти две системные переменные задаем учетку админа в кейклоке
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'admin'
      # прописываем тип БД кейклока. h2 - sql inmemory database
      DB_VENDOR: 'h2'
      # пароль для ключа tls.key, сгенерированного через keycloak_certs_and_truststore_generator.sh
      # будет использоваться кейклоком как пароль от
      # /opt/jboss/keycloak/standalone/configuration/keystores/https-keystore.jks, который он сгенерит из
      # самоподписанных ключа tls.key и серта tks.crt
#      SERVER_KEYSTORE_PASSWORD: 'keycloak-password'
      KEYCLOAK_LOGLEVEL: "INFO"
      KEYCLOAK_IMPORT: "/tmp/example-realm.json"
    volumes:
#      - ./imports/keycloak/tls.crt:/etc/x509/https/tls.crt
#      - ./imports/keycloak/tls.key:/etc/x509/https/tls.key
      - ./imports/keycloak/realm-config.json:/tmp/example-realm.json
    ports:
      - "8080:8080"

  openldap:
    image: rroemhild/test-openldap
    container_name: ldap-local
    networks:
      - keycloak-ldap
    ports:
      - "10389:10389"
      - "10636:10636"

networks:
  keycloak-ldap: